version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    networks: 
      - mongo

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    networks: 
      - mongo

networks:
  mongo:
    driver: bridge